import * as React from 'react';
/**
 * This file is auto-generated by CI. It pulls down all the sub applications associatd with a given admin root and
 * imports them.
 */
import apps from './apps.js';
import { AdminRoot } from '../lib/admin-root/AdminRoot';


const App: React.SFC = () => {
    return (
    <AdminRoot
      audience={process.env.AUTH0_AUDIENCE}
      domain={process.env.AUTH0_DOMAIN}
      client_id={process.env.AUTH0_CLIENT_ID}
      subApps={apps}
    />

    )
}

export default App;
